---
title: 'Probability Theory and random '
format:
  html:
    code-fold: true
jupyter: python3
---

# Probability theory
a branch of mathematics concerned with the analysis of random data distributions. It helps us to understand the probabilities and likelihood of an event based on understanding distribution from their past events.

```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
```

Create a array with normal and exponential distribution

```{python}
# Number of samples
num_samples = 1000

# Generate random data from a normal distribution
random_data = np.random.normal(0,10,num_samples)

# Generate random data from an exponential distribution
scale_parameter = 10  # Adjust this parameter as needed
exponential_data = np.random.exponential(scale=scale_parameter, size=num_samples)
```

Draw the Probability distribution for both

```{python}
#| scrolled: true
# Plotting the histograms
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.hist(random_data, bins=30, density=True, alpha=0.7, color='blue', label='Random (Normal)')
plt.title('Random (Normal) Distribution')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()

plt.subplot(1, 2, 2)
plt.hist(exponential_data, bins=30, density=True, alpha=0.7, color='green', label='Exponential')
plt.title('Exponential Distribution')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()

plt.tight_layout()
plt.show()
```

The probability density function produces the likelihood of values of the continuous random variable.It helps us to understand what is probability to get value between a particular range with given distribution 

```{python}
#| scrolled: true
x=np.sort(random_data)
pdf = norm.pdf(x, loc=0, scale=10)

# Plot PDF
plt.plot(x, pdf, color='blue', label='PDF of Normal Distribution')
plt.title('Probability Density Function (PDF) of a Normal Distribution')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()
plt.show()
```

```{python}
x=np.sort(exponential_data)
pdf = norm.pdf(x, loc=0, scale=10)

# Plot PDF
plt.plot(x, pdf, color='blue', label='PDF of Normal Distribution')
plt.title('Probability Density Function (PDF) of a Normal Distribution')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()
plt.show()
```

CDF finds the cumulative probability for the given value. it finds what is the probability to get the value low from the given value.

```{python}
x = np.sort(random_data)
cdf = norm.cdf(x, loc=0, scale=10)

# Plot CDF
plt.plot(x, cdf, color='blue', label='CDF of Normal Distribution')
plt.title('Cumulative Distribution Function (CDF) of a Normal Distribution')
plt.xlabel('Value')
plt.ylabel('Cumulative Probability')
plt.legend()
plt.show()
```

```{python}
x = np.sort(exponential_data)
cdf = norm.cdf(x, loc=0, scale=10)

# Plot CDF
plt.plot(x, cdf, color='blue', label='CDF of Normal Distribution')
plt.title('Cumulative Distribution Function (CDF) of a Normal Distribution')
plt.xlabel('Value')
plt.ylabel('Cumulative Probability')
plt.legend()
plt.show()
```

Probability theory includes the methods to understand the data distribution. We have examine the pdf and Cdf of two different distributions one is random other is exponentiation 

# Reference links:

[1] https://www.britannica.com/science/probability-theory

[2] https://igppweb.ucsd.edu/~agnew/Courses/Sio223a/sio223a.chap2.pdf

[3] https://numpy.org/doc/1.16/reference/routines.random.html

[4] https://www.scribbr.com/statistics/normal-distribution

[5] https://byjus.com/maths/probability-density-function

[6] https://byjus.com/maths/cumulative-distribution-function/


